// boostrap app w/ some data
export const INITIAL_SHOWS = [{
  "id": 301562,
  "seriesName": "Chewing Gum",
  "aliases": [],
  "banner": "graphical/301562-g2.jpg",
  "seriesId": "",
  "status": "Continuing",
  "firstAired": "2015-10-06",
  "network": "E4",
  "networkId": "",
  "runtime": "25",
  "genre": ["Comedy"],
  "overview": "The life of Tracey and the mishaps of her neighbourhood, friends and family.",
  "lastUpdated": 1482935226,
  "airsDayOfWeek": "Tuesday",
  "airsTime": "10:00 PM",
  "rating": "",
  "imdbId": "tt5097050",
  "zap2itId": "",
  "added": "2015-10-06 06:03:22",
  "addedBy": 396427,
  "siteRating": 7,
  "siteRatingCount": 3,
  "inQueue": false
}, {
  "id": 321060,
  "seriesName": "The OA",
  "aliases": [],
  "banner": "graphical/321060-g3.jpg",
  "seriesId": "",
  "status": "Continuing",
  "firstAired": "2016-12-16",
  "network": "Netflix",
  "networkId": "",
  "runtime": "60",
  "genre": ["Drama", "Mystery", "Science-Fiction"],
  "overview": "Prairie Johnson, blind as a child, comes home to the community she grew up in with her sight restored. Some hail her a miracle, others a dangerous mystery, but Prairie won’t talk with the FBI or her parents about the seven years she went missing.",
  "lastUpdated": 1482923918,
  "airsDayOfWeek": "Friday",
  "airsTime": "3:00 AM",
  "rating": "",
  "imdbId": "tt4635282",
  "zap2itId": "",
  "added": "2016-12-12 10:16:55",
  "addedBy": 396427,
  "siteRating": 9.2,
  "siteRatingCount": 9,
  "inQueue": false
}, {
  "id": 314544,
  "seriesName": "Travelers (2016)",
  "aliases": [],
  "banner": "graphical/314544-g.jpg",
  "seriesId": "",
  "status": "Continuing",
  "firstAired": "2016-10-17",
  "network": "Showcase (CA)",
  "networkId": "",
  "runtime": "45",
  "genre": ["Action", "Science-Fiction"],
  "overview": "Hundreds of years from now, the last surviving humans discover the means of sending consciousness back through time, directly into people in the 21st century. These \"travelers\" assume the lives of seemingly random people, while secretly working as teams to perform missions in order to save humanity from a terrible future.",
  "lastUpdated": 1482917908,
  "airsDayOfWeek": "Monday",
  "airsTime": "9:00 PM",
  "rating": "TV-14",
  "imdbId": "tt5651844",
  "zap2itId": "",
  "added": "2016-07-19 01:49:30",
  "addedBy": 428880,
  "siteRating": 7,
  "siteRatingCount": 8,
  "inQueue": false
}]